### ISSUE TITLE
Iterable.first quick fix fails on nested array index lookup

### ISSUE THREAD

**Issue by imsamgarg** [charlescyt/pyramid_lint#31]
### Is there an existing issue for this bug?

- [X] I have searched the [existing issues](https://github.com/charlescyt/pyramid_lint/issues).

### Bug Description

Here's the issue.

[list_first.webm](https://github.com/charlescyt/pyramid_lint/assets/34547038/62432359-16e3-49e5-952c-37a0ca536866)

### Steps to Reproduce

Use any nested array lookup with the main array lookup index to be 0.

**Comment by charlescyt** [comment]
We probably should use 
```dart
if (!analysisError.sourceRange.covers(node.sourceRange)) return;
```
instead of
```dart
if (!analysisError.sourceRange.intersects(node.sourceRange)) return;
```

**Comment by imsamgarg** [comment]
Yeah this fixes the issue.

**Comment by charlescyt** [comment]
I think it makes sense to use `covers` instead of `intersects` for all the quick fixes as well.
#33 only changes `prefer_iterable_first` and `prefer_iterable_last`
