### ISSUE TITLE
Swap if and else expression showing up everywhere in the condition block

### ISSUE THREAD

**Issue by imsamgarg** [charlescyt/pyramid_lint#32]
### Is there an existing issue for this bug?

- [X] I have searched the [existing issues](https://github.com/charlescyt/pyramid_lint/issues).

### Bug Description

With the current implementation, this assist shows up everywhere in the condition block, You can see this in the screenshot below.

![if_else](https://github.com/charlescyt/pyramid_lint/assets/34547038/e7266718-8a80-4936-b4c8-54019d11863e)

It should not be visible in the if-else block but only on the if-else keywords, condition expression, or the whole line.

### Steps to Reproduce

Use any if-else condition.

**Comment by charlescyt** [comment]
Yeah. I agree that the assist should not be available when hovering over the "then" or "else" statement.
