### ISSUE TITLE
avoid_nested_if lint showing for else if blocks also

### ISSUE THREAD

**Issue by imsamgarg** [charlescyt/pyramid_lint#43]
### Is there an existing issue for this bug?

- [X] I have searched the [existing issues](https://github.com/charlescyt/pyramid_lint/issues).

### Bug Description

When we define multiple conditions using else if this lint is showing up. 

![image](https://github.com/charlescyt/pyramid_lint/assets/34547038/4b487545-7bdc-4265-9ca6-ecafc4666a20)

From programmer's point of view they are not nested. But from the compiler's pov they are indeed nested. Is there any way by which we can handle this case?

### Steps to Reproduce

Declare multiple else if blocks

```dart
  if (a == 1) {
  } else if (a == 2) {
  } else if (a == 3) {
  } else {}
```

**Comment by charlescyt** [comment]
Sure. I will try to fix it today.
