### ISSUE TITLE
avoid_public_members_in_states lint should respect @visibleForTesting

### ISSUE THREAD

**Issue by jogboms** [charlescyt/pyramid_lint#46]
### Is there an existing issue for this bug?

- [X] I have searched the [existing issues](https://github.com/charlescyt/pyramid_lint/issues).

### Bug Description

The should respect the [@visibleForTesting](https://pub.dev/documentation/meta/latest/meta/visibleForTesting-constant.html) annotation from [package:meta](https://pub.dev/packages/meta)

### Steps to Reproduce

Any `State` class with a public property exposed only for the test environment with the annotation

**Comment by charlescyt** [comment]
Thanks for the suggestion!
I will update the lint to ignore public fields & methods with `visibleForTesting` annotation.

**Comment by jogboms** [comment]
Amazing work @charlescyt
